# Generated by Django 4.0.3 on 2022-05-18 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('picture', models.ImageField(blank=True, default='userimages/default.jpg', null=True, upload_to='userimages/')),
                ('fathername', models.CharField(blank=True, max_length=500, null=True)),
                ('mothername', models.CharField(blank=True, max_length=500, null=True)),
                ('city', models.CharField(blank=True, max_length=20, null=True)),
                ('state', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=500, null=True)),
                ('dateofbirth', models.DateField(blank=True, null=True)),
                ('phonenumber', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('currentaddress', models.CharField(blank=True, max_length=100, null=True)),
                ('permanentaddress', models.CharField(blank=True, max_length=100, null=True)),
                ('jobprofile', models.CharField(blank=True, max_length=20, null=True)),
                ('joblocation', models.CharField(blank=True, max_length=20, null=True)),
                ('companyname', models.CharField(blank=True, max_length=20, null=True)),
                ('skill', models.TextField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('social_github', models.CharField(blank=True, max_length=200, null=True)),
                ('social_linkedin', models.CharField(blank=True, max_length=200, null=True)),
                ('social_twitter', models.CharField(blank=True, max_length=200, null=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
