# Generated by Django 4.0.3 on 2022-05-16 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0002_profile_bio_profile_city_profile_companyname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='default.jpg', null=True, upload_to='myimage'),
        ),
    ]
