# Generated by Django 4.0.3 on 2022-05-16 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0003_alter_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='user_id',
        ),
    ]
