# Generated by Django 4.0.3 on 2022-05-21 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='post',
            new_name='postform',
        ),
    ]
