# Generated by Django 4.0.3 on 2022-05-22 17:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('post', '0002_rename_post_postform'),
    ]

    operations = [
        migrations.CreateModel(
            name='posteventform',
            fields=[
                ('eventname', models.CharField(max_length=200)),
                ('organiser', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='postform',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profiles'),
        ),
    ]
