# Generated by Django 4.0.3 on 2022-05-31 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_posteventform_postform_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='posteventform',
            name='last_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
