# Generated by Django 4.0.3 on 2022-06-02 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_posteventform_discription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posteventform',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
